### ISSUE TITLE
無法安裝顯示網路設定錯誤，Duckdns可以外網登入

### ISSUE THREAD

**Issue by ZhiMingChang** [cnk700i/havcs#41]
![image](https://user-images.githubusercontent.com/76430534/110779563-a46d4400-829e-11eb-9049-7d69b71ed588.png)

**Comment by ZhiMingChang** [comment]
Logger: homeassistant.config_entries
Source: helpers/network.py:124
First occurred: 下午7:12:42 (1 occurrences)
Last logged: 下午7:12:42

Error setting up entry 主配置[configuration.yml] for havcs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 248, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/havcs/__init__.py", line 254, in async_setup_entry
    http_manager = hass.data[DOMAIN][DATA_HAVCS_HTTP_MANAGER] = HavcsHttpManager(hass, conf.get(CONF_HTTP, {}).get(CONF_HA_URL, get_url(hass)), DEVICE_CONFIG_SCHEMA, SETTINGS_CONFIG_SCHEMA)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 84, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 124, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by 836154942** [comment]
the same problem,同问
