### ISSUE TITLE
最新版本ha安装havcs出错

### ISSUE THREAD

**Issue by lightvsliang** [cnk700i/havcs#43]
Logger: homeassistant.config_entries
Source: helpers/network.py:123
First occurred: 23:40:44 (1 occurrences)
Last logged: 23:40:44

Error setting up entry 主配置[configuration.yml] for havcs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/havcs/__init__.py", line 254, in async_setup_entry
    http_manager = hass.data[DOMAIN][DATA_HAVCS_HTTP_MANAGER] = HavcsHttpManager(hass, conf.get(CONF_HTTP, {}).get(CONF_HA_URL, get_url(hass)), DEVICE_CONFIG_SCHEMA, SETTINGS_CONFIG_SCHEMA)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 83, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 123, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
__INFO：

是因为ha_url通过HA内置方法自动识别时，由于新版HA会优先读取旧版本.storage/core.config的url配置，可能会因此导致不准确。_怎么解？

**Comment by 836154942** [comment]
同问，说下下解决思路，

**Comment by Depressboy** [comment]
我也遇到了同样的问题，安装不成功

**Comment by chen-sky** [comment]
我也遇到了同样的问题，安装不成功

**Comment by chen-sky** [comment]
修改 .storage 文件夹里的core.config 找到 "external_url": "https://你的域名:端口",

**Comment by varequan** [comment]
其实是HA的配置文件更新了，你可能还是沿用旧版的HA配置，
只要你在configuration.yaml文件的homeassistant:下加上以下配置即可
 
internal_url: "内网访问地址"
