### ISSUE TITLE
天猫精灵重新绑定后更新设备log报错

### ISSUE THREAD

**Issue by rangerzhou** [cnk700i/havcs#48]
```
2021-12-08 23:10:53 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 314, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 546, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'invalid HTTP method'"
2021-12-08 23:10:59 DEBUG (MainThread) [custom_components.havcs] [mqtt] -------- start handle task from mqtt at 2021-12-08 23:10:59 --------
2021-12-08 23:10:59 DEBUG (MainThread) [custom_components.havcs] [mqtt] raw message: {'content': '{"extensions":{},"header":{"messageId":"86dd3311-d621-4519-8324-e37e933f5360","name":"DiscoveryDevices","namespace":"AliGenie.Iot.Device.Discovery","payLoadVersion":1},"payload":{"accessToken":"06e5c97696500cd1e6dea16464ddbea0477635f5"}}', 'headers': {'Authorization': 'Bearer 06e5c97696500cd1e6dea16464ddbea0477635f5'}, 'msgId': '7b823693c76dd99591544c518f7acf8e', 'platform': 'aligenie', 'msgType': 'cmnd'}
2021-12-08 23:10:59 INFO (MainThread) [custom_components.havcs.aligenie] [aligenie] Handle Request:
{'extensions': {}, 'header': {'messageId': '86dd3311-d621-4519-8324-e37e933f5360', 'name': 'DiscoveryDevices', 'namespace': 'AliGenie.Iot.Device.Discovery', 'payLoadVersion': 1}, 'payload': {'accessToken': '06e5c97696500cd1e6dea16464ddbea0477635f5'}}
2021-12-08 23:10:59 INFO (MainThread) [custom_components.havcs.aligenie] [aligenie] Respnose:
{'header': {'messageId': '86dd3311-d621-4519-8324-e37e933f5360', 'name': 'DiscoveryDevicesResponse', 'namespace': 'AliGenie.Iot.Device.Discovery', 'payLoadVersion': 1}, 'payload': {'devices': []}}
2021-12-08 23:10:59 DEBUG (MainThread) [custom_components.havcs] [mqtt] -------- mqtt task finish at 2021-12-08 23:10:59, Running time: 0.167872s --------
```

**Comment by rangerzhou** [comment]
小度同样识别不出设备

```
2021-12-08 22:56:21 DEBUG (MainThread) [custom_components.havcs] [mqtt] -------- start handle task from mqtt at 2021-12-08 22:56:21 --------
2021-12-08 22:56:21 DEBUG (MainThread) [custom_components.havcs] [mqtt] raw message: {'content': '{"header":{"payloadVersion":"1","name":"DiscoverAppliancesRequest","namespace":"DuerOS.ConnectedHome.Discovery","messageId":"_Smarthome_61b0c79525db98.32419576"},"payload":{"accessToken":"9cb91a753dbb03c871e98db5339038bd059f7b80","openUid":"b6a431a3dd25302baee30aa569bebc3d"}}', 'headers': {'Authorization': 'Bearer 9cb91a753dbb03c871e98db5339038bd059f7b80'}, 'msgId': '754ef51614ea26d57ab25439daa8f54c', 'platform': 'dueros', 'msgType': 'cmnd'}
2021-12-08 22:56:21 INFO (MainThread) [custom_components.havcs.dueros] [dueros] Handle Request:
{'header': {'payloadVersion': '1', 'name': 'DiscoverAppliancesRequest', 'namespace': 'DuerOS.ConnectedHome.Discovery', 'messageId': '_Smarthome_61b0c79525db98.32419576'}, 'payload': {'accessToken': '9cb91a753dbb03c871e98db5339038bd059f7b80', 'openUid': 'b6a431a3dd25302baee30aa569bebc3d'}}
2021-12-08 22:56:21 INFO (MainThread) [custom_components.havcs.dueros] [dueros] Respnose:
{'header': {'payloadVersion': '1', 'name': 'DiscoverAppliancesResponse', 'namespace': 'DuerOS.ConnectedHome.Discovery', 'messageId': '_Smarthome_61b0c79525db98.32419576'}, 'payload': {'discoveredAppliances': []}}
2021-12-08 22:56:21 DEBUG (MainThread) [custom_components.havcs] [mqtt] -------- mqtt task finish at 2021-12-08 22:56:21, Running time: 0.161244s --------
2021-12-08 23:05:34 INFO (MainThread) [custom_components.havcs] loading device info from file
```


MQTT 连接成功
```
2021-12-08 22:34:35 INFO (MainThread) [custom_components.havcs] [mqtt] get hello message: 
****************************************************
***欢迎使用"havcs智能音箱接入Home Assistant方案"***
*********当你看到此信息，说明mqtt已正常工作*********
****************************************************
```
